// Generated by tools/generate-population-contract/generate.mjs. Do not edit.

export const POPULATION_CONTRACT = Object.freeze({
  "version": 1,
  "baselinePopulation": 8130371000,
  "baselineTimestamp": "2026-01-01T00:00:00Z",
  "birthsPerSecond": 4.28,
  "deathsPerSecond": 2.06,
  "source": "UN WPP 2024 Medium Variant (static)",
  "lastAnchorYear": 2026,
  "continents": {
    "Africa": {
      "populationShare": 0.1787512340601262
    },
    "Asia": {
      "populationShare": 0.5916414085088684
    },
    "Europe": {
      "populationShare": 0.09441086305992581
    },
    "North_America": {
      "populationShare": 0.07552869044794065
    },
    "South_America": {
      "populationShare": 0.054128894821024134
    },
    "Oceania": {
      "populationShare": 0.005538770632848981
    },
    "Antarctica": {
      "populationShare": 1.3846926582122452e-7
    }
  }
});

export const STATIC_ANCHOR = Object.freeze({
  baselinePopulation: POPULATION_CONTRACT.baselinePopulation,
  baselineTimestamp: POPULATION_CONTRACT.baselineTimestamp,
  baselineTimestampMs: Date.parse(POPULATION_CONTRACT.baselineTimestamp),
  birthsPerSecond: POPULATION_CONTRACT.birthsPerSecond,
  deathsPerSecond: POPULATION_CONTRACT.deathsPerSecond,
  source: POPULATION_CONTRACT.source,
  lastAnchorYear: POPULATION_CONTRACT.lastAnchorYear,
});

export const BASE_CONTINENTS = Object.freeze(Object.fromEntries(
  Object.entries(POPULATION_CONTRACT.continents).map(([name, data]) => [name, Object.freeze({
    population: Math.floor(STATIC_ANCHOR.baselinePopulation * data.populationShare),
    birthsPerSecond: STATIC_ANCHOR.birthsPerSecond * data.populationShare,
    deathsPerSecond: STATIC_ANCHOR.deathsPerSecond * data.populationShare,
  })]),
));
