import json
import unittest
from pathlib import Path

from shared.population import BASE_CONTINENTS, STATIC_ANCHOR


REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = REPO_ROOT / "shared" / "population-anchor.json"
JS_CONSUMER_PATH = REPO_ROOT / "apps" / "screensaver-web" / "src" / "population.js"


class PopulationContractTests(unittest.TestCase):
    def test_contract_shares_are_normalized(self):
        contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
        total_share = sum(item["populationShare"] for item in contract["continents"].values())
        self.assertAlmostEqual(total_share, 1.0, places=12)

    def test_python_consumer_matches_global_anchor(self):
        self.assertEqual(
            sum(item["population"] for item in BASE_CONTINENTS.values()),
            STATIC_ANCHOR["baseline_population"] - 3,
        )
        self.assertEqual(STATIC_ANCHOR["baseline_timestamp"], "2026-01-01T00:00:00Z")

    def test_javascript_consumer_is_generated(self):
        consumer = JS_CONSUMER_PATH.read_text(encoding="utf-8")
        self.assertIn("Generated by tools/generate-population-contract/generate.mjs", consumer)
        self.assertIn("POPULATION_CONTRACT", consumer)


if __name__ == "__main__":
    unittest.main()