# Generated by tools/generate-population-contract/generate.mjs. Do not edit.

import json
from pathlib import Path

CONTRACT_PATH = Path(__file__).with_name("population-anchor.json")
CONTRACT = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))

STATE_SCHEMA_VERSION = CONTRACT["version"]
BIRTHS_PER_SEC = float(CONTRACT["birthsPerSecond"])
DEATHS_PER_SEC = float(CONTRACT["deathsPerSecond"])
STATIC_ANCHOR = {
    "baseline_population": int(CONTRACT["baselinePopulation"]),
    "baseline_timestamp": CONTRACT["baselineTimestamp"],
    "births_per_second": BIRTHS_PER_SEC,
    "deaths_per_second": DEATHS_PER_SEC,
    "source": CONTRACT["source"],
    "last_anchor_year": int(CONTRACT["lastAnchorYear"]),
}
BASE_CONTINENTS = {
    name: {
        "population": int(STATIC_ANCHOR["baseline_population"] * data["populationShare"]),
        "births_per_sec": BIRTHS_PER_SEC * data["populationShare"],
        "deaths_per_sec": DEATHS_PER_SEC * data["populationShare"],
    }
    for name, data in CONTRACT["continents"].items()
}
