import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..");
const contractPath = path.join(repoRoot, "shared", "population-anchor.json");
const pythonOutputPath = path.join(repoRoot, "shared", "population.py");
const javascriptOutputPath = path.join(repoRoot, "apps", "screensaver-web", "src", "population.js");

function assertValidContract(contract) {
  const requiredNumbers = [
    contract.baselinePopulation,
    contract.birthsPerSecond,
    contract.deathsPerSecond,
    contract.lastAnchorYear,
  ];
  if (!Number.isInteger(contract.version) || contract.version < 1) {
    throw new Error("Contract version must be a positive integer.");
  }
  if (requiredNumbers.some((value) => !Number.isFinite(value) || value < 0)) {
    throw new Error("Contract numeric values must be finite and non-negative.");
  }
  if (Number.isNaN(Date.parse(contract.baselineTimestamp))) {
    throw new Error("Contract baselineTimestamp must be an ISO timestamp.");
  }
  const shares = Object.values(contract.continents ?? {}).map(({ populationShare }) => populationShare);
  if (shares.length === 0 || shares.some((share) => !Number.isFinite(share) || share < 0)) {
    throw new Error("Contract continents must contain non-negative population shares.");
  }
  const shareTotal = shares.reduce((total, share) => total + share, 0);
  if (Math.abs(shareTotal - 1) > 1e-12) {
    throw new Error(`Continent population shares must sum to 1; received ${shareTotal}.`);
  }
}

function renderPython(contractJson) {
  return `# Generated by tools/generate-population-contract/generate.mjs. Do not edit.\n\nimport json\nfrom pathlib import Path\n\nCONTRACT_PATH = Path(__file__).with_name("population-anchor.json")\nCONTRACT = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))\n\nSTATE_SCHEMA_VERSION = CONTRACT["version"]\nBIRTHS_PER_SEC = float(CONTRACT["birthsPerSecond"])\nDEATHS_PER_SEC = float(CONTRACT["deathsPerSecond"])\nSTATIC_ANCHOR = {\n    "baseline_population": int(CONTRACT["baselinePopulation"]),\n    "baseline_timestamp": CONTRACT["baselineTimestamp"],\n    "births_per_second": BIRTHS_PER_SEC,\n    "deaths_per_second": DEATHS_PER_SEC,\n    "source": CONTRACT["source"],\n    "last_anchor_year": int(CONTRACT["lastAnchorYear"]),\n}\nBASE_CONTINENTS = {\n    name: {\n        "population": int(STATIC_ANCHOR["baseline_population"] * data["populationShare"]),\n        "births_per_sec": BIRTHS_PER_SEC * data["populationShare"],\n        "deaths_per_sec": DEATHS_PER_SEC * data["populationShare"],\n    }\n    for name, data in CONTRACT["continents"].items()\n}\n`;
}

function renderJavaScript(contractJson) {
  return `// Generated by tools/generate-population-contract/generate.mjs. Do not edit.\n\nexport const POPULATION_CONTRACT = Object.freeze(${contractJson});\n\nexport const STATIC_ANCHOR = Object.freeze({\n  baselinePopulation: POPULATION_CONTRACT.baselinePopulation,\n  baselineTimestamp: POPULATION_CONTRACT.baselineTimestamp,\n  baselineTimestampMs: Date.parse(POPULATION_CONTRACT.baselineTimestamp),\n  birthsPerSecond: POPULATION_CONTRACT.birthsPerSecond,\n  deathsPerSecond: POPULATION_CONTRACT.deathsPerSecond,\n  source: POPULATION_CONTRACT.source,\n  lastAnchorYear: POPULATION_CONTRACT.lastAnchorYear,\n});\n\nexport const BASE_CONTINENTS = Object.freeze(Object.fromEntries(\n  Object.entries(POPULATION_CONTRACT.continents).map(([name, data]) => [name, Object.freeze({\n    population: STATIC_ANCHOR.baselinePopulation * data.populationShare,\n    birthsPerSecond: STATIC_ANCHOR.birthsPerSecond * data.populationShare,\n    deathsPerSecond: STATIC_ANCHOR.deathsPerSecond * data.populationShare,\n  })]),\n));\n`;
}

const contract = JSON.parse(await fs.readFile(contractPath, "utf8"));
assertValidContract(contract);
const contractJson = JSON.stringify(contract, null, 2);
const pythonConsumer = renderPython(contractJson);
const javascriptConsumer = renderJavaScript(contractJson).replace(
  "population: STATIC_ANCHOR.baselinePopulation * data.populationShare,",
  "population: Math.floor(STATIC_ANCHOR.baselinePopulation * data.populationShare),",
);

await fs.mkdir(path.dirname(javascriptOutputPath), { recursive: true });
await fs.writeFile(pythonOutputPath, pythonConsumer, "utf8");
await fs.writeFile(javascriptOutputPath, javascriptConsumer, "utf8");